### ISSUE TITLE
Docker build with filebeats => 7.9.0 failed

### ISSUE THREAD

**Issue by barthex** [hasnat/beats-processor-replace#1]
I'm going to build a module for filebeat 7.17.5. During a compilation by Dockerfile with
ARG BEATS_VERSION=7.9.3

build failed with error:

```
=> ERROR [builder 6/7] RUN go get -d ./...                                                                                                                              28.6s
------
 > [builder 6/7] RUN go get -d ./...:
#13 25.89 code in directory /go/src/go.elastic.co/apm expects import "go.elastic.co/apm/v2"
#13 25.92 package go.elastic.co/apm/transport: unrecognized import path "go.elastic.co/apm/transport": reading https://go.elastic.co/apm/transport?go-get=1: 404 Not Found
------
executor failed running [/bin/sh -c go get -d ./...]: exit code: 1
```

**Comment by hasnat** [comment]
example Dockerfile here is bit old now, you'd probably need to update golang version to match 7.17.5's go version; which likely will then make you move to go mod lastly the beats/filebeat version compatiblity.
I can try updating example sometime during the week.

**Comment by barthex** [comment]
Thanks for quick response. The highest version of Filebeat for which compilation succeed is 7.8.1. For version 7.9.0, the apm agent has been added.

**Comment by barthex** [comment]
@hasnat I resolved my task by using the filebeat script preprocessor, there is no need to rebuild for a new version of filebeat 

```
processors:
      - script:
          lang: javascript
          id: replace_incident
          source: >
            function process(event) { event.Put("incident", event.Get("request.fake_body").replace("incident=","")); }
      - decode_json_fields:
          fields: ["incident"]
```

**Comment by hasnat** [comment]
Nice. Didn't know about this. Guess this feature makes this processor redundant.

**Comment by hasnat** [comment]
not updating to newer filebeat and closing this, since we have alternate ways for newer versions.
